workspace:
  base: /go
  path: src/github.com/CyCoreSystems/cycore-web
pipeline:
  build:
    image: golang:1.10
    pull: true
    commands:
      - mkdir -p /go/bin /go/src
      - go get github.com/revel/cmd/revel
      - go get -u github.com/golang/dep/cmd/dep/...
      - dep ensure
      - revel build github.com/CyCoreSystems/cycore-web ../tmp prod >> /dev/null
      - mv ../tmp .
  publish:
    image: plugins/docker
    repo: quay.io/cycore/web
    tags:
      - "${DRONE_COMMIT}"
    registry: quay.io
    email: ulexus@gmail.com
    secrets: [ docker_username, docker_password ]
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    namespace: web
    deployment: cycore
    container: web
    secrets: [ kubernetes_username, kubernetes_token, kubernetes_server ]
    repo: quay.io/cycore/web
    tag:
      - "${DRONE_COMMIT}"

